import { Component } from 'preact';
import { observer } from 'preact-mobx';
import List from 'preact-material-components/List';
import Dialog from 'preact-material-components/Dialog';
import TextField from 'preact-material-components/TextField';
import Button from 'preact-material-components/Button';
import 'preact-material-components/TextField/style.css';
import 'preact-material-components/List/style.css';
import 'preact-material-components/Button/style.css';
import 'preact-material-components/Dialog/style.css';
import 'preact-material-components/Button/style.css';
import style from './style.css';
import firebase, { firestore } from '../../state/firebase';
import { when } from 'mobx';

@observer
export default class ContactsList extends Component {

	inviteContact(e) {
		e.preventDefault();
		const contactEmail = document.querySelector('#email-field').value;
		document.querySelector('#email-field').value = null;

		// todo: validate email more throroughly
		if (contactEmail == firebase.auth().currentUser.email) throw "can't invite yourself silly!";

		// todo - maybe use transaction(s) somewhere in here?
		// check if this contact has already been invited or added,
		// todo - check in a cached list of emails in state/ later
		Promise.all([
			firestore.collection('users/' + firebase.auth().currentUser.uid + '/outgoing_invitations')
				.where('email', '==', contactEmail)
				.get()
				.then(snapshot => {
						if (!snapshot.empty) {
							return Promise.reject("contact has already been invited");
						}
					}
				),
			firestore.collection('users/' + firebase.auth().currentUser.uid + '/contacts')
				.where('email', '==', contactEmail)
				.get()
				.then(snapshot => {
						if (!snapshot.empty) {
							return Promise.reject("contact has already been added");
						}
					}
				)
		]).then(_ => this.inviteContactHelper(contactEmail));
	}

	inviteContactHelper(contactEmail) {
		let contactSnapshot;

		// todo - maybe use transaction(s) somewhere in here?
		// query firestore for user with contactEmail
		firestore.collection('users').where('email', '==', contactEmail)
			.get()
			.then(snapshot => {
					if(!snapshot.empty) {
						contactSnapshot = snapshot.docs[0];
						console.log('user_: ', contactSnapshot);
					}
				}
			)
			.then(() => {
				// if no such user, lookup email in future_users
				if(!contactSnapshot) {
					return firestore.collection('future_users').where('email', '==', contactEmail)
						.get()
						.then(
							snapshot => {
								if(!snapshot.empty) {
									contactSnapshot = snapshot.docs[0];
									console.log('future_user_: ', contactSnapshot);
								}
							}
						);
				}
			})
			.then(() => {
				// if no such future_user, create future_user doc
				if(!contactSnapshot) {
					return firestore.collection('future_users').doc().get()
						.then(futureUserSnapshot => {
							contactSnapshot = futureUserSnapshot;
							futureUserSnapshot.ref.set({email: contactEmail});
						})
						.catch(err => {
							console.error('Error adding future_user: ', err);
							throw err;
							// todo - this is presumably the type of thing a transaction would be useful for
						});
				}
			})
			.then(() => {
				// todo - refactor users collection?
					// use autogenerated ids?
					// lookup by email or keep a ref cached somewhere?
				const currentUserRef = firestore.collection('users').doc(firebase.auth().currentUser.uid);
				// add contact email and ref to outgoing invitations sub-col of current user
				currentUserRef.collection('outgoing_invitations').doc()
					.set({email: contactEmail, contactRef: contactSnapshot.ref})
					.catch(err => console.error('Error adding outgoingInvitation: ', err));

				// add current user ref to incoming invitations sub-col of contact
				contactSnapshot.ref.collection('incoming_invitations').doc()
					.set({userRef: currentUserRef})
					.catch(err => console.error('Error adding incomingInvitation: ', err));
			});
	}

	acceptInvitation(fromUserRef) {
		console.log('accept ', fromUserRef);
		const currentUserRef = firestore.collection('users').doc(firebase.auth().currentUser.uid);

		// create contact doc
		fromUserRef.get()
			.then(fromUserSnap => {
				currentUserRef.collection('contacts').doc()
					.set({userRef: fromUserRef, email: fromUserSnap.data().email})
					.catch(err => console.error('Error adding contact: ', err));
			});

		// delete incoming invitations doc
		this.deleteIncomingInvitationDoc(fromUserRef, currentUserRef);
		// set isAccepted flag to true in fromUser's outgoing invitation doc
		fromUserRef.collection('outgoing_invitations').where('contactRef', '==', currentUserRef).get()
			.then(snapshot => snapshot.docs[0].ref.update({isAccepted: true}))
			.catch(err => console.error('Error updating isAccepted in outgoing_invitations doc: ', err));
	}

	declineInvitation(fromUserRef) {
		console.log('decline ', fromUserRef);
		const currentUserRef = firestore.collection('users').doc(firebase.auth().currentUser.uid);
		this.deleteIncomingInvitationDoc(fromUserRef, currentUserRef);
		// set isDeclined flag to true in fromUser's outgoing invitation doc
		fromUserRef.collection('outgoing_invitations').where('contactRef', '==', currentUserRef).get()
			.then(snapshot => snapshot.docs[0].ref.update({isDeclined: true}))
			.catch(err => console.error('Error updating isDeclined in outgoing_invitations doc: ', err));
	}

	deleteIncomingInvitationDoc(fromUserRef, currentUserRef) {
		currentUserRef.collection('incoming_invitations').where('userRef', '==', fromUserRef).get()
			.then(snapshot => snapshot.docs[0].ref.delete())
			.catch(err => console.error('Error deleting incoming_invitations doc: ', err));
	}

	render({ contactStore }) {
		return (
			<div class={`${style.contactsList} page`}>
				<List avatar-list>
					<List.Item onClick={()=>{this.inviteDialog.MDComponent.show();}}>
						<List.ItemGraphic>add_circle_outline</List.ItemGraphic>
						<List.TextContainer>Invite a Contact</List.TextContainer>
					</List.Item>

					{contactStore.incomingInvitations.size > 0 &&
					<List.Item>
						<List.TextContainer>
							Incoming Invitations ({contactStore.incomingInvitations.size})
						</List.TextContainer>
					</List.Item>
					}
					{contactStore.incomingInvitations.size > 0 &&
						Array.from(contactStore.incomingInvitations.values()).map(fromUser => (
							<List.Item>
								<List.ItemGraphic>perm_identity</List.ItemGraphic>
								<List.TextContainer>{fromUser.fromUserName}</List.TextContainer>
								<List.ItemMeta>
									<div className={`${style.buttons}`}>
										<Button dense onClick={this.declineInvitation.bind(this, fromUser.fromUserRef)}>
											Decline
										</Button>
										<Button outlined dense onClick={this.acceptInvitation.bind(this,
											fromUser.fromUserRef)}>
											Accept
										</Button>
									</div>
								</List.ItemMeta>
							</List.Item>
						))
					}

					{contactStore.outgoingInvitations.size > 0 &&
						<List.Item>
							<List.TextContainer>
								Outgoing Invitations ({contactStore.outgoingInvitations.size})
							</List.TextContainer>
						</List.Item>
					}
					{contactStore.outgoingInvitations.size > 0 &&
						Array.from(contactStore.outgoingInvitations.values()).map(invitation => (
							<List.Item>
								<List.ItemGraphic>perm_identity</List.ItemGraphic>
								<List.TextContainer>{invitation.email}</List.TextContainer>
							</List.Item>
						))
					}
				</List>

				<Dialog ref={el => { this.inviteDialog = el; }} onAccept={this.inviteContact.bind(this)}>
					<Dialog.Header>Invite a Contact</Dialog.Header>
					<Dialog.Body>
						<TextField label="Email" outlined id="email-field"/>
					</Dialog.Body>
					<Dialog.Footer>
						<Dialog.FooterButton accept={true}>Save</Dialog.FooterButton>
					</Dialog.Footer>
				</Dialog>
			</div>
		);
	}
}
